version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      - spark-network

  spark-master:
    image: apache/spark:3.5.0
    tty: true
    stdin_open: true
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - spark-network

  spark-worker:
    image: apache/spark:3.5.0
    tty: true
    stdin_open: true
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge