services:
  data-warehouse:
    image: postgres:16
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: amazing_mspr_db
    networks:
      - spark-network
    volumes:
      - pgdatawarehouse:/var/lib/postgresql/data

networks:
  spark-network:
    driver: bridge

volumes:
  pgdatawarehouse: