version: "3.8"

services:
  minio:
    image: "minio/minio"
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge
