name: mspr822

services:

  nodemain:
    image: apache/spark
    command: /opt/spark/sbin/start-master.sh
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - /datadisk/data/:/tmp/dataset/ # customize with local folder containing data files

  worker1:
    image: apache/spark
    command: /opt/spark/sbin/start-worker.sh spark://nodemain:7077 -c 8 -m 10G
    depends_on:
      nodemain:
        condition: service_started
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - /datadisk/data/:/tmp/dataset/ # customize with local folder containing data files

  worker2:
      image: apache/spark
      command: /opt/spark/sbin/start-worker.sh spark://nodemain:7077 -c 8 -m 10G
      depends_on:
        nodemain:
          condition: service_started
      environment:
        - SPARK_NO_DAEMONIZE=true
      volumes:
        - /datadisk/data/:/tmp/dataset/ # customize with local folder containing data files